export const categoryMappings = [
    ['Advertising', 'Business_Portfolio'],
    ['Air Travel', 'Travel_Vacation'],
    ['Alcohol & Bars','Alcohol_Bars'],
    ['ATM Fee','Misc'],
    ['Auto & Transport','Travel_Vacation'],
    ['Auto Insurance','Car_Insurance'],
    ['Bank Fee','Misc'],
    ['Bonus','Supplemental_Income'],
    ['Books','Books_Podcasts'],
    ['Books & Supplies','Books_Podcasts'],
    ['Business Services','Business_Portfolio'],
    ['Buy','Investment_Transfer'],
    ['Charity','Gifts_Donations'],
    ['Clothing','Shopping'],
    ['Coffee Shops','Restaurants'],
    ['Credit Card Payment','Investment_Transfer'],
    ['Deposit','Investment_Transfer'],
    ['Dividend & Cap Gains','Investment_Transfer'],
    ['Doctor','Health_Fitness'],
    ['Education','School_Job'],
    ['Electronics & Software','Misc'],
    ['Entertainment','Entertainment'],
    ['Fast Food','Fast_Food'],
    ['Fees & Charges','Misc'],
    ['Food & Dining','Restaurants'],
    ['Furnishings','Shopping'],
    ['Gambling','Misc'],
    ['Gas & Fuel','Gasoline'],
    ['Gift','Gifts_Donations'],
    ['Gifts & Donations','Gifts_Donations'],
    ['Groceries','Groceries'],
    ['Gym','Health_Fitness'],
    ['Hair','Haircut'],
    ['Health & Fitness','Health_Fitness'],
    ['Health Insurance','Health_Fitness'],
    ['Hide from Budgets & Trends','Investment_Transfer'],
    ['Hobbies','Shopping'],
    ['Home Insurance','Home_Insurance'],
    ['Home Supplies','Household_Hygiene'],
    ['Hotel','Travel_Vacation'],
    ['Income','Supplemental_Income'],
    ['Interest Income','Supplemental_Income'],
    ['Internet','Internet'],
    ['Investments','Investment_Transfer'],
    ['Job Expenses','School_Job'],
    ['Late Fee','Misc'],
    ['Laundry','Household_Hygiene'],
    ['Legal','Business_Portfolio'],
    ['Loan Insurance','Misc'],
    ['Loan Payment','Investment_Transfer'],
    ['Loan Principal','Misc'],
    ['Loans','Misc'],
    ['Misc Expenses','Misc'],
    ['Mobile Phone','Cell_Phone'],
    ['Mortgage & Rent','Rent'],
    ['Movies & DVDs','Entertainment'],
    ['Music','Entertainment'],
    ['Parking','Travel_Vacation'],
    ['Paycheck','Salary'],
    ['Personal Care','Household_Hygiene'],
    ['Pharmacy','Health_Fitness'],
    ['Property Tax','Investment_Transfer'],
    ['REI','Real_Estate_Investment'],
    ['Reimbursement','Misc'],
    ['Rental Car & Taxi','Travel_Vacation'],
    ['Restaurants','Restaurants'],
    ['Ride Share','Travel_Vacation'],
    ['Sell','Investment_Transfer'],
    ['Service & Parts','Car'],
    ['Shipping','Business_Portfolio'],
    ['Shopping','Shopping'],
    ['Sporting Events','Entertainment'],
    ['Sporting Goods','Shopping'],
    ['Sports','Health_Fitness'],
    ['State Tax','Misc'],
    ['Student Loan','School_Job'],
    ['Taxes','Misc'],
    ['Trade Commissions','Investment_Transfer'],
    ['Transfer','Investment_Transfer'],
    ['Travel','Travel_Vacation'],
    ['Utilities','Utilities'],
    ['Vacation','Travel_Vacation'],
    ['Withdrawal','Investment_Transfer'],
];

export const fireCategories = [
    'Rent',
    'Internet',
    'Cell_Phone',
    'Utilities',
    'Groceries',
    'Car_Insurance',
    'Home_Insurance',
    'Property_Tax',
    'Gasoline',
    'Car',
    'Household_Hygiene',
    'Haircut',
    'Books_Podcasts',
    'School_Job',
    'Health_Fitness',
    'Real_Estate_Investment',
    '',
    '',
    '',
    '',
    'Restaurants',
    'Fast_Food',
    'Alcohol_Bars',
    'Entertainment',
    'Shopping',
    'Travel_Vacation',
    'Gifts_Donations',
    'Business_Portfolio',
    'Misc',
    '',
    '',
    '',
    '',
    '',
    'Salary',
    'Supplemental_Income',
    '',
    'Investment_Transfer',
];