export const categoryMappings = [
    ['Advertising', 'Business_Portfolio'],
    ['Air Travel', 'Travel_Vacation'],
    ['Alcohol/Bars','Alcohol_Bars'],
    ['ATM Fee','Misc'],
    ['Automotive','Travel_Vacation'],
    ['Auto Insurance','Car_Insurance'],
    ['Auto Loan','Car'],
    ['Bank Fee','Misc'],
    ['Other Income','Supplemental_Income'],
    ['Books','Books_Podcasts'],
    ['Books & Supplies','Books_Podcasts'],
    ['Business Miscellaneous','Business_Portfolio'],
    ['Buy','Investment_Transfer'],
    ['Charitable Giving','Gifts_Donations'],
    ['Clothing/Shoes','Shopping'],
    ['Coffee Shops','Restaurants'],
    ['Credit Card Payments','Investment_Transfer'],
    ['Deposit','Investment_Transfer'],
    ['Dividend & Cap Gains','Investment_Transfer'],
    ['Education','School_Job'],
    ['Electronics','Shopping'],
    ['Entertainment','Entertainment'],
    ['Fast Food','Fast_Food'],
    ['Fees & Charges','Misc'],
    ['Food & Dining','Restaurants'],
    ['Furnishings','Shopping'],
    ['Gambling','Misc'],
    ['Gasoline/Fuel','Gasoline'],
    ['Gifts','Gifts_Donations'],
    ['Gifts & Donations','Gifts_Donations'],
    ['Groceries','Groceries'],
    ['Gym','Health_Fitness'],
    ['Hair','Haircut'],
    ['Healthcare/Medical','Health_Fitness'],
    ['Health/Fitness','Health_Fitness'],
    ['Health Insurance','Health_Fitness'],
    ['Hide from Budgets & Trends','Investment_Transfer'],
    ['Hobbies','Shopping'],
    ['Home Improvement','Real_Estate_Investment'],
    ['Home Insurance','Home_Insurance'],
    ['Home Maintenance','Real_Estate_Investment'],
    ['Home Supplies','Household_Hygiene'],
    ['Hotel','Travel_Vacation'],
    ['HSA Contribution','Salary'],
    ['Income','Supplemental_Income'],
    ['Interest','Supplemental_Income'],
    ['Internet','Internet'],
    ['Investment Income','Supplemental_Income'],
    ['Investments','Investment_Transfer'],
    ['Job Expenses','School_Job'],
    ['Late Fee','Misc'],
    ['Laundry','Household_Hygiene'],
    ['Legal','Business_Portfolio'],
    ['Loan Insurance','Misc'],
    ['Loan Payment','Investment_Transfer'],
    ['Loan Principal','Misc'],
    ['Loans','Misc'],
    ['Magazines and Blogs','Entertainment'],
    ['Miscellaneous','Misc'],
    ['Mobile Phone','Cell_Phone'],
    ['Mortgages','Rent'],
    ['Movies & DVDs','Entertainment'],
    ['Music','Entertainment'],
    ['Parking','Travel_Vacation'],
    ['Paychecks/Salary','Salary'],
    ['Personal Care','Household_Hygiene'],
    ['Pharmacy','Health_Fitness'],
    ['Property Tax','Investment_Transfer'],
    ['REI','Real_Estate_Investment'],
    ['Reimbursement','Misc'],
    ['Rent','Rent'],
    ['Rental Car & Taxi','Travel_Vacation'],
    ['Rental Income','Supplemental_Income'],
    ['Restaurants','Restaurants'],
    ['Ride Share','Travel_Vacation'],
    ['Sell','Investment_Transfer'],
    ['Service & Parts','Car'],
    ['Shipping','Business_Portfolio'],
    ['Shopping','Shopping'],
    ['Sporting Events','Entertainment'],
    ['Sporting Goods','Shopping'],
    ['Sports','Health_Fitness'],
    ['State Tax','Misc'],
    ['Student Loans','School_Job'],
    ['Taxes','Misc'],
    ['Trade Commissions','Investment_Transfer'],
    ['Transfers','Investment_Transfer'],
    ['Travel','Travel_Vacation'],
    ['Utilities','Utilities'],
    ['Vacation','Travel_Vacation'],
    ['Withdrawal','Investment_Transfer'],
    ['Work/Job','School_Job'],
    ['401(k) Contributions','Salary'],
];

export const fireCategories = [
    'Rent',
    'Internet',
    'Cell_Phone',
    'Utilities',
    'Groceries',
    'Car_Insurance',
    'Home_Insurance',
    'Property_Tax',
    'Gasoline',
    'Car',
    'Household_Hygiene',
    'Haircut',
    'Books_Podcasts',
    'School_Job',
    'Health_Fitness',
    'Real_Estate_Investment',
    '',
    '',
    '',
    '',
    'Restaurants',
    'Fast_Food',
    'Alcohol_Bars',
    'Entertainment',
    'Shopping',
    'Travel_Vacation',
    'Gifts_Donations',
    'Business_Portfolio',
    'Misc',
    '',
    '',
    '',
    '',
    '',
    'Salary',
    'Supplemental_Income',
    '',
    'Investment_Transfer',
];