export const categoryMappings = [
    ['Advertising', FireCategories.BUSINESS_PORTFOLIO],
    ['Air Travel', FireCategories.TRAVEL_VACATION],
    ['Alcohol/Bars', FireCategories.ALCOHOL_BARS],
    ['ATM Fee', FireCategories.MISC],
    ['Automotive', FireCategories.TRAVEL_VACATION],
    ['Auto Insurance', FireCategories.CAR_INSURANCE],
    ['Auto Loan', FireCategories.CAR],
    ['Bank Fee', FireCategories.MISC],
    ['Other Income', FireCategories.SUPPLEMENTAL_INCOME],
    ['Books', FireCategories.BOOKS_PODCASTS],
    ['Books & Supplies', FireCategories.BOOKS_PODCASTS],
    ['Business Miscellaneous', FireCategories.BUSINESS_PORTFOLIO],
    ['Buy', FireCategories.INVESTMENT_TRANSFER],
    ['Charitable Giving', FireCategories.GIFTS_DONATIONS],
    ['Clothing/Shoes', FireCategories.SHOPPING],
    ['Coffee Shops', FireCategories.RESTAURANTS],
    ['Credit Card Payments', FireCategories.INVESTMENT_TRANSFER],
    ['Deposit', FireCategories.INVESTMENT_TRANSFER],
    ['Dividend & Cap Gains', FireCategories.INVESTMENT_TRANSFER],
    ['Education', FireCategories.SCHOOL_JOB],
    ['Electronics', FireCategories.SHOPPING],
    ['Entertainment', FireCategories.ENTERTAINMENT],
    ['Fast Food', FireCategories.FAST_FOOD],
    ['Fees & Charges', FireCategories.MISC],
    ['Food & Dining', FireCategories.RESTAURANTS],
    ['Furnishings', FireCategories.SHOPPING],
    ['Gambling', FireCategories.MISC],
    ['Gasoline/Fuel', FireCategories.GASOLINE],
    ['Gifts', FireCategories.GIFTS_DONATIONS],
    ['Gifts & Donations', FireCategories.GIFTS_DONATIONS],
    ['Groceries', FireCategories.GROCERIES],
    ['Gym', FireCategories.HEALTH_FITNESS],
    ['Hair', FireCategories.HAIRCUT],
    ['Healthcare/Medical', FireCategories.HEALTH_FITNESS],
    ['Health/Fitness', FireCategories.HEALTH_FITNESS],
    ['Health Insurance', FireCategories.HEALTH_FITNESS],
    ['Hide from Budgets & Trends', FireCategories.INVESTMENT_TRANSFER],
    ['Hobbies', FireCategories.SHOPPING],
    ['Home Improvement', FireCategories.REAL_ESTATE_INVESTMENT],
    ['Home Insurance', FireCategories.HOME_INSURANCE],
    ['Home Maintenance', FireCategories.REAL_ESTATE_INVESTMENT],
    ['Home Supplies', FireCategories.HOUSEHOLD_HYGENE],
    ['Hotel', FireCategories.TRAVEL_VACATION],
    ['HSA Contribution', FireCategories.SALARY],
    ['Income', FireCategories.SUPPLEMENTAL_INCOME],
    ['Interest', FireCategories.SUPPLEMENTAL_INCOME],
    ['Internet', FireCategories.INTERNET],
    ['Investment Income', FireCategories.SUPPLEMENTAL_INCOME],
    ['Investments', FireCategories.INVESTMENT_TRANSFER],
    ['Job Expenses', FireCategories.SCHOOL_JOB],
    ['Late Fee', FireCategories.MISC],
    ['Laundry', FireCategories.HOUSEHOLD_HYGENE],
    ['Legal', FireCategories.BUSINESS_PORTFOLIO],
    ['Loan Insurance', FireCategories.MISC],
    ['Loan Payment', FireCategories.INVESTMENT_TRANSFER],
    ['Loan Principal', FireCategories.INVESTMENT_TRANSFER],
    ['Loans', FireCategories.INVESTMENT_TRANSFER],
    ['Magazines and Blogs', FireCategories.ENTERTAINMENT],
    ['Miscellaneous', FireCategories.MISC],
    ['Mobile Phone', FireCategories.CELL_PHONE],
    ['Mortgages', FireCategories.RENT],
    ['Movies & DVDs', FireCategories.ENTERTAINMENT],
    ['Music', FireCategories.ENTERTAINMENT],
    ['Parking', FireCategories.TRAVEL_VACATION],
    ['Paychecks/Salary', FireCategories.SALARY],
    ['Personal Care', FireCategories.HOUSEHOLD_HYGENE],
    ['Pharmacy', FireCategories.HEALTH_FITNESS],
    ['Property Tax', FireCategories.INVESTMENT_TRANSFER],
    ['REI', FireCategories.REAL_ESTATE_INVESTMENT],
    ['Reimbursement', FireCategories.MISC],
    ['Rent', FireCategories.RENT],
    ['Rental Car & Taxi', FireCategories.TRAVEL_VACATION],
    ['Rental Income', FireCategories.SUPPLEMENTAL_INCOME],
    ['Restaurants', FireCategories.RESTAURANTS],
    ['Retirement Contributions', FireCategories.SALARY],
    ['Ride Share', FireCategories.TRAVEL_VACATION],
    ['Sell', FireCategories.INVESTMENT_TRANSFER],
    ['Service & Parts', FireCategories.CAR],
    ['Shipping', FireCategories.BUSINESS_PORTFOLIO],
    ['Shopping', FireCategories.SHOPPING],
    ['Sporting Events', FireCategories.ENTERTAINMENT],
    ['Sporting Goods', FireCategories.SHOPPING],
    ['Sports', FireCategories.HEALTH_FITNESS],
    ['State Tax', FireCategories.MISC],
    ['Student Loans', FireCategories.SCHOOL_JOB],
    ['Taxes', FireCategories.MISC],
    ['Trade Commissions', FireCategories.INVESTMENT_TRANSFER],
    ['Transfers', FireCategories.INVESTMENT_TRANSFER],
    ['Travel', FireCategories.TRAVEL_VACATION],
    ['Utilities', FireCategories.UTILITIES],
    ['Vacation', FireCategories.TRAVEL_VACATION],
    ['Withdrawal', FireCategories.INVESTMENT_TRANSFER],
    ['Work/Job', FireCategories.SCHOOL_JOB],
    ['401(k) Contributions', FireCategories.SALARY],
];

import { MonarchCategories } from './monarchCategories';

// Monarch categories -> FIRE categories
export const monarchToFireMappings = [
    // Income
    [MonarchCategories.PAYCHECKS, FireCategories.SALARY],
    [MonarchCategories.INTEREST, FireCategories.SUPPLEMENTAL_INCOME],
    [MonarchCategories.BUSINESS_INCOME, FireCategories.SUPPLEMENTAL_INCOME],
    [MonarchCategories.OTHER_INCOME, FireCategories.SUPPLEMENTAL_INCOME],
    [MonarchCategories.HSA_CONTRIBUTION, FireCategories.SALARY],
    [MonarchCategories.RENTAL_INCOME, FireCategories.SUPPLEMENTAL_INCOME],

    // Expenses - Gifts & Donations
    [MonarchCategories.CHARITY, FireCategories.GIFTS_DONATIONS],
    [MonarchCategories.GIFTS, FireCategories.GIFTS_DONATIONS],
    [MonarchCategories.DONATIONS, FireCategories.GIFTS_DONATIONS],

    // Expenses - Auto & Transport
    [MonarchCategories.AUTO_PAYMENT, FireCategories.AUTO_PAYMENT],
    [MonarchCategories.PUBLIC_TRANSIT, FireCategories.TRAVEL_VACATION],
    [MonarchCategories.GAS, FireCategories.GASOLINE],
    [MonarchCategories.AUTO_MAINTENANCE, FireCategories.CAR],
    [MonarchCategories.PARKING_TOLLS, FireCategories.TRAVEL_VACATION],
    [MonarchCategories.TAXI_RIDE_SHARES, FireCategories.TRAVEL_VACATION],

    // Expenses - Housing
    [MonarchCategories.MORTGAGE, FireCategories.RENT],
    [MonarchCategories.RENT, FireCategories.RENT],
    [MonarchCategories.HOME_IMPROVEMENT, FireCategories.HOUSEHOLD_HYGIENE],

    // Expenses - Bills & Utilities
    [MonarchCategories.GARBAGE, FireCategories.UTILITIES],
    [MonarchCategories.WATER, FireCategories.UTILITIES],
    [MonarchCategories.GAS_ELECTRIC, FireCategories.UTILITIES],
    [MonarchCategories.INTERNET_CABLE, FireCategories.INTERNET],
    [MonarchCategories.PHONE, FireCategories.CELL_PHONE],

    // Expenses - Food & Dining
    [MonarchCategories.GROCERIES, FireCategories.GROCERIES],
    [MonarchCategories.RESTAURANTS_BARS, FireCategories.RESTAURANTS],
    [MonarchCategories.COFFEE_SHOPS, FireCategories.RESTAURANTS],
    [MonarchCategories.FAST_FOOD, FireCategories.FAST_FOOD],
    [MonarchCategories.ALCOHOL_BARS, FireCategories.ALCOHOL_BARS],

    // Expenses - Travel & Lifestyle
    [MonarchCategories.TRAVEL_VACATION, FireCategories.TRAVEL_VACATION],
    [MonarchCategories.ENTERTAINMENT_RECREATION, FireCategories.ENTERTAINMENT],
    [MonarchCategories.PERSONAL, FireCategories.HOUSEHOLD_HYGIENE],
    [MonarchCategories.PETS, FireCategories.MISCELLANEOUS],
    [MonarchCategories.FUN_MONEY, FireCategories.MISCELLANEOUS],

    // Expenses - Shopping
    [MonarchCategories.SHOPPING, FireCategories.SHOPPING],
    [MonarchCategories.CLOTHING, FireCategories.SHOPPING],
    [MonarchCategories.FURNITURE_HOUSEWARES, FireCategories.SHOPPING],
    [MonarchCategories.ELECTRONICS, FireCategories.SHOPPING],

    // Expenses - Children
    [MonarchCategories.CHILD_CARE, FireCategories.MISCELLANEOUS],
    [MonarchCategories.CHILD_ACTIVITIES, FireCategories.MISCELLANEOUS],

    // Expenses - Education
    [MonarchCategories.STUDENT_LOANS, FireCategories.SCHOOL_JOB],
    [MonarchCategories.EDUCATION, FireCategories.SCHOOL_JOB],

    // Expenses - Health & Wellness
    [MonarchCategories.MEDICAL, FireCategories.HEALTH_FITNESS],
    [MonarchCategories.DENTIST, FireCategories.HEALTH_FITNESS],
    [MonarchCategories.FITNESS, FireCategories.HEALTH_FITNESS],
    [MonarchCategories.GYM, FireCategories.HEALTH_FITNESS],

    // Expenses - Financial
    [MonarchCategories.LOAN_REPAYMENT, FireCategories.INVESTMENT_TRANSFER],
    [MonarchCategories.FINANCIAL_LEGAL_SERVICES, FireCategories.MISC],
    [MonarchCategories.FINANCIAL_FEES, FireCategories.MISC],
    [MonarchCategories.CASH_ATM, FireCategories.MISC],
    [MonarchCategories.INSURANCE, FireCategories.INSURANCE],
    [MonarchCategories.TAXES, FireCategories.MISC],

    // Expenses - Other
    [MonarchCategories.UNCATEGORIZED, FireCategories.MISC],
    [MonarchCategories.CHECK, FireCategories.MISC],
    [MonarchCategories.MISCELLANEOUS, FireCategories.MISC],

    // Business
    [MonarchCategories.ADVERTISING_PROMOTION, FireCategories.BUSINESS_PORTFOLIO],
    [MonarchCategories.BUSINESS_UTILITIES_COMMUNICATION, FireCategories.BUSINESS_PORTFOLIO],
    [MonarchCategories.EMPLOYEE_WAGES_CONTRACT_LABOR, FireCategories.BUSINESS_PORTFOLIO],
    [MonarchCategories.BUSINESS_TRAVEL_MEALS, FireCategories.BUSINESS_PORTFOLIO],
    [MonarchCategories.BUSINESS_AUTO_EXPENSES, FireCategories.BUSINESS_PORTFOLIO],
    [MonarchCategories.BUSINESS_INSURANCE, FireCategories.BUSINESS_PORTFOLIO],
    [MonarchCategories.OFFICE_SUPPLIES_EXPENSES, FireCategories.BUSINESS_PORTFOLIO],
    [MonarchCategories.OFFICE_RENT, FireCategories.BUSINESS_PORTFOLIO],
    [MonarchCategories.POSTAGE_SHIPPING, FireCategories.BUSINESS_PORTFOLIO],
    [MonarchCategories.ONLINE_SERVICES, FireCategories.BUSINESS_PORTFOLIO],
    [MonarchCategories.REI, FireCategories.REAL_ESTATE_INVESTMENT],

    // Transfers
    [MonarchCategories.TRANSFER, FireCategories.INVESTMENT_TRANSFER],
    [MonarchCategories.CREDIT_CARD_PAYMENT, FireCategories.INVESTMENT_TRANSFER],
    [MonarchCategories.BALANCE_ADJUSTMENTS, FireCategories.INVESTMENT_TRANSFER],
];

export const FireCategories = {
  RENT: 'Rent',
  INTERNET: 'Internet',
  CELL_PHONE: 'Cell_Phone',
  UTILITIES: 'Utilities',
  GROCERIES: 'Groceries',
  CAR_INSURANCE: 'Car_Insurance',
  HOME_INSURANCE: 'Home_Insurance',
  PROPERTY_TAX: 'Property_Tax',
  GASOLINE: 'Gasoline',
  CAR: 'Car',
  HOUSEHOLD_HYGIENE: 'Household_Hygiene',
  HAIRCUT: 'Haircut',
  BOOKS_PODCASTS: 'Books_Podcasts',
  SCHOOL_JOB: 'School_Job',
  HEALTH_FITNESS: 'Health_Fitness',
  REAL_ESTATE_INVESTMENT: 'Real_Estate_Investment',
  RESTAURANTS: 'Restaurants',
  FAST_FOOD: 'Fast_Food',
  ALCOHOL_BARS: 'Alcohol_Bars',
  ENTERTAINMENT: 'Entertainment',
  SHOPPING: 'Shopping',
  TRAVEL_VACATION: 'Travel_Vacation',
  GIFTS_DONATIONS: 'Gifts_Donations',
  BUSINESS_PORTFOLIO: 'Business_Portfolio',
  MISC: 'Misc',
  SALARY: 'Salary',
  SUPPLEMENTAL_INCOME: 'Supplemental_Income',
  INVESTMENT_TRANSFER: 'Investment_Transfer'
};

export const MappingOrder = [
    FireCategories.RENT,
    FireCategories.INTERNET,
    FireCategories.CELL_PHONE,
    FireCategories.UTILITIES,
    FireCategories.GROCERIES,
    FireCategories.CAR_INSURANCE,
    FireCategories.HOME_INSURANCE,
    FireCategories.PROPERTY_TAX,
    FireCategories.GASOLINE,
    FireCategories.CAR,
    FireCategories.HOUSEHOLD_HYGIENE,
    FireCategories.HAIRCUT,
    FireCategories.BOOKS_PODCASTS,
    FireCategories.SCHOOL_JOB,
    FireCategories.HEALTH_FITNESS,
    FireCategories.REAL_ESTATE_INVESTMENT,
    '',
    '',
    '',
    '',
    FireCategories.RESTAURANTS,
    FireCategories.FAST_FOOD,
    FireCategories.ALCOHOL_BARS,
    FireCategories.ENTERTAINMENT,
    FireCategories.SHOPPING,
    FireCategories.TRAVEL_VACATION,
    FireCategories.GIFTS_DONATIONS,
    FireCategories.BUSINESS_PORTFOLIO,
    FireCategories.MISC,
    '',
    '',
    '',
    '',
    '',
    FireCategories.SALARY,
    FireCategories.SUPPLEMENTAL_INCOME,
    '',
    FireCategories.INVESTMENT_TRANSFER,
];