export const externalCategories = [
    'Advertising',
    'Air Travel',
    'Alcohol/Bars',
    'ATM Fee',
    'Automotive',
    'Auto Insurance',
    'Auto Loan',
    'Bank Fee',
    'Other Income',
    'Books',
    'Books & Supplies',
    'Business Miscellaneous',
    'Buy',
    'Charitable Giving',
    'Clothing/Shoes',
    'Coffee Shops',
    'Credit Card Payments',
    'Deposit',
    'Dividend & Cap Gains',
    'Education',
    'Electronics',
    'Entertainment',
    'Fast Food',
    'Fees & Charges',
    'Food & Dining',
    'Furnishings',
    'Gambling',
    'Gasoline/Fuel',
    'Gifts',
    'Gifts & Donations',
    'Groceries',
    'Gym',
    'Hair',
    'Healthcare/Medical',
    'Health/Fitness',
    'Health Insurance',
    'Hide from Budgets & Trends',
    'Hobbies',
    'Home Improvement',
    'Home Insurance',
    'Home Maintenance',
    'Home Supplies',
    'Hotel',
    'HSA Contribution',
    'Income',
    'Interest',
    'Internet',
    'Investment Income',
    'Investments',
    'Job Expenses',
    'Late Fee',
    'Laundry',
    'Legal',
    'Loan Insurance',
    'Loan Payment',
    'Loan Principal',
    'Loans',
    'Magazines and Blogs',
    'Miscellaneous',
    'Mobile Phone',
    'Mortgages',
    'Movies & DVDs',
    'Music',
    'Parking',
    'Paychecks/Salary',
    'Personal Care',
    'Pharmacy',
    'Property Tax',
    'REI',
    'Reimbursement',
    'Rent',
    'Rental Car & Taxi',
    'Rental Income',
    'Retirement Contributions',
    'Restaurants',
    'Ride Share',
    'Sell',
    'Service & Parts',
    'Shipping',
    'Shopping',
    'Sporting Events',
    'Sporting Goods',
    'Sports',
    'State Tax',
    'Student Loans',
    'Taxes',
    'Trade Commissions',
    'Transfers',
    'Travel',
    'Utilities',
    'Vacation',
    'Withdrawal',
    'Work/Job',
    '401(k) Contributions',
];