export const mintCategories = [
    'Advertising',
    'Air Travel',
    'Alcohol & Bars',
    'ATM Fee',
    'Auto & Transport',
    'Auto Insurance',
    'Bank Fee',
    'Bonus',
    'Books',
    'Books & Supplies',
    'Business Services',
    'Buy',
    'Charity',
    'Clothing',
    'Coffee Shops',
    'Credit Card Payment',
    'Deposit',
    'Dividend & Cap Gains',
    'Doctor',
    'Education',
    'Electronics & Software',
    'Entertainment',
    'Fast Food',
    'Fees & Charges',
    'Food & Dining',
    'Furnishings',
    'Gambling',
    'Gas & Fuel',
    'Gift',
    'Gifts & Donations',
    'Groceries',
    'Gym',
    'Hair',
    'Health & Fitness',
    'Health Insurance',
    'Hide from Budgets & Trends',
    'Hobbies',
    'Home Insurance',
    'Home Supplies',
    'Hotel',
    'Income',
    'Interest Income',
    'Internet',
    'Investments',
    'Job Expenses',
    'Late Fee',
    'Laundry',
    'Legal',
    'Loan Insurance',
    'Loan Payment',
    'Loan Principal',
    'Loans',
    'Misc Expenses',
    'Mobile Phone',
    'Mortgage & Rent',
    'Movies & DVDs',
    'Music',
    'Parking',
    'Paycheck',
    'Personal Care',
    'Pharmacy',
    'Property Tax',
    'REI',
    'Reimbursement',
    'Rental Car & Taxi',
    'Restaurants',
    'Ride Share',
    'Sell',
    'Service & Parts',
    'Shipping',
    'Shopping',
    'Sporting Events',
    'Sporting Goods',
    'Sports',
    'State Tax',
    'Student Loan',
    'Taxes',
    'Trade Commissions',
    'Transfer',
    'Travel',
    'Utilities',
    'Vacation',
    'Withdrawal',
];